name    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: Contolodon/android_kernel_common-5.10
          path: kernel_source

      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential flex libelf-dev libssl-dev python3 clang lld llvm gcc-aarch64-linux-gnu

      - name: Clone Your Device Tree
        run: |
          rm -rf kernel_source/arch/arm64/boot/dts/vendor/qcom
          git clone https://github.com/Contolodon/android_kernel_xiaomi_sm7435-devicetrees.git -b lineage-23 kernel_source/arch/arm64/boot/dts/vendor/qcom

      - name: Build DTBO
        run: |
          cd kernel_source
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make gki_defconfig
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- dtbo.img

