name: Build DTBO Only

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dtc
        run: sudo apt-get update && sudo apt-get install -y device-tree-compiler build-essential

      - name: Clone Device Tree
        run: |
          git clone https://github.com/Contolodon/android_kernel_xiaomi_sm7435-devicetrees.git -b lineage-23 devicetree

      - name: Build DTBO
        run: |
          cd devicetree
          cpp -nostdinc -undef -x assembler-with-cpp \
            -I. -Ibindings \
            qcom/parrot-gpu.dtsi temp.dts
          dtc -@ -I dts -O dtb -o gpu-oc.dtbo temp.dts

      - uses: actions/upload-artifact@v4
        with:
          name: gpu-oc-dtbo
          path: devicetree/gpu-oc.dtbo
